version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev-environment
    volumes:
      # Mount your project directory
      - ./workspace:/workspace
      # Persist Go modules cache
      - go-mod-cache:/go/pkg/mod
      # Persist Node.js cache
      - node-cache:/home/developer/.npm
    working_dir: /workspace
    # Keep container running
    tty: true
    stdin_open: true
    # Basic environment variables
    environment:
      - GOPROXY=https://proxy.golang.org,direct
      - NODE_ENV=development
    ports:
      # Essential development ports
      - "3000:3000"   # Node.js apps
      - "8080:8080"   # Go web apps

volumes:
  go-mod-cache:
  node-cache: