services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    container_name: devenv
    volumes:
      # Mount your project directory
      - ./workspace:/workspace
      - /mnt/c/Users/Vincenzo/Unity:/Unity
      # Persist Go modules cache
      - go-mod-cache:/go/pkg/mod
      # Persist Node.js cache
      - node-cache:/home/developer/.npm
      # Mount Docker socket to control host Docker
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    # Keep container running
    tty: true
    stdin_open: true
    env_file:
      - .env
    # Basic environment variables
    environment:
      - GOPROXY=https://proxy.golang.org,direct
      - NODE_ENV=development
    ports:
      # Essential development ports
      - "3001:3000"   # Node.js apps
      - "8080:8080"   # Go web apps

volumes:
  go-mod-cache:
  node-cache:
